apiVersion: v1
kind: Secret
metadata:
  name: nacos-mysql-secret # Secret 名称
type: Opaque
data:
  # 将 'your_nacos_password' 替换为你上面创建的 MySQL 用户密码
  # 注意：密码需要经过 Base64 编码
  # 你可以在 Linux/macOS 终端执行: echo -n 'your_nacos_password' | base64
  MYSQL_SERVICE_PASSWORD: <你的Base64编码后的密码> # 例如： eW91cl9uYWNvc19wYXNzd29yZA==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm # ConfigMap 名称
data:
  # Nacos 配置文件 (application.properties 格式)
  # 注意：这里使用环境变量来引用 Secret 中的密码
  # Nacos 启动脚本通常会识别这些 MYSQL_SERVICE_* 环境变量
  mysql.db.name: "nacos_config"  # 数据库名
  mysql.port: "3306"             # MySQL 端口
  mysql.user: "nacos_user"       # MySQL 用户名
  # mysql.password: 从 Secret 获取