apiVersion: v1
kind: Service
metadata:
  name: nacos-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: nacos
  ports:
    - port: 8848
      targetPort: 8848
      nodePort: 30848
