spring:
  datasource:
    url: jdbc:mysql://localhost:3306/letsvpn?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 90508888
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.letsvpn.user: DEBUG # 确保你自己的包也是 DEBUG

