# auth-service-all-in-one.yaml

apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: default
type: Opaque
data:
  # spring.datasource.password: LetsvpnUser@2025 (Base64 encoded)
  MYSQL_PASSWORD: TGV0c3ZwblVzZXJAMjAyNQ==
  # REDIS_PASSWORD: <your_redis_password_base64_encoded>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: default
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_APPLICATION_NAME: "auth-service"

  SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR: "nacos.default.svc.cluster.local:8848"
  SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE: "public"
  SPRING_CLOUD_NACOS_DISCOVERY_ENABLED: "true"

  SPRING_DATASOURCE_URL: "jdbc:mysql://10.10.0.1:3306/letsvpn?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "letsvpn_user"

  SPRING_REDIS_HOST: "10.10.0.1"
  SPRING_REDIS_PORT: "6379"

  JAVA_OPTS: "-Duser.timezone=Asia/Shanghai -Xms256m -Xmx512m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: solosoldier385/auth-service:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: auth-service-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: http
